import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "react-hot-toast";

import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import ClientComponent from "./clientComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientComponent>
          <GoogleOAuthProvider clientId="543687300801-cd9t1sbfvndl8j89vviknvn51skaneb5.apps.googleusercontent.com">
            {children}
            <Toaster />
            <ReactQueryDevtools />
          </GoogleOAuthProvider>
        </ClientComponent>
      </body>
    </html>
  );
}
